<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exception Handling | Level-Up Java</title>
    <link href="styles.css" rel="stylesheet" />
</head>

<body>

    <nav class="navigation-std">

        <ul class="ul-remove-bullet nav-pills">

            <li class="ul-inline-item nav-pills-decor">
                <a class="link" href="/">Previous</a>
            </li>

            <li class="ul-inline-item nav-pills-decor">
                <a class="link" href="/">Home</a>
            </li>

            <li class="ul-inline-item nav-pills-decor">
                <a class="link" href="/">Next</a>
            </li>

        </ul>

    </nav>

    <h1 class="h1-basic">Exception Handling</h1>
    <hr>

    <br>

    <div class="desc-container desc-container-center desc-std">
        <ul>
            <li>
                <p>
                    <i>Exception</i> is an undesired state that arises during run-time when instructions are executed.
                    Basically
                    a run-time error.
                </p>
            </li>
            <li>
                <p>
                    Five keywords used for exception handling in Java are: <strong>try</strong>, <strong>catch</strong>,
                    <strong>throw</strong>, <strong>throws</strong>, and <strong>finally</strong>.
                    <ul>
                        <li>
                            <p>
                                <strong>try</strong> - this block contains the set of statements that might cause
                                exceptions.
                            </p>
                        </li>
                        <li>
                            <p>
                                <strong>catch</strong> - this block will execute if an exception has occured in the
                                <i>try</i> block and perform necesssary steps, hence preventing abnormal termination of
                                the
                                program.
                            </p>
                        </li>
                        <li>
                            <p>
                                <strong>throw</strong> - to manually throw an exception the <i>throw</i> keyword is
                                used.
                                Although system-generated exceptions are automatically thrown by the Java run-time
                                system.
                            </p>
                        </li>
                        <li>
                            <p>
                                <strong>throws</strong> - any exception which is thrown out of a method must be
                                specified by
                                a <i>throws</i> clause.
                            </p>
                        </li>
                        <li>
                            <p>
                                <strong>finally</strong> - set of statements which must be executed after <i>try</i>
                                block
                                completes must be put inside the <i>finally</i> block.
                            </p>
                        </li>
                    </ul>
                </p>
            </li>
            <li>
                <p>
                    The <strong>Throwable</strong> class is at the top of the exception class hierarchy. All exception
                    types are subclasses of the built-in class <i>Throwable</i>. There are two sub-classes of
                    <i>Throwable</i> named <strong>Error</strong> and <strong>Exception</strong>.
                </p>
                <p title="Throwable class hierarchy" style="text-align:center">
                    <img src="assets\images\LUJ-EH-01.png" alt="Throwable class hierarchy" width=500
                        class="img-responsive" />
                </p>
            </li>
            <li>
                <p>
                    The <strong>Error</strong> class defines exceptions that are not expected to be caught under normal
                    circumstances by our program. Exceptions of type <i>Error</i> are used by the Java run-time system
                    to indicate errors having to do with the run-time environment, itself. Ex.: Stack overflow error.
                </p>
            </li>
            <li>
                <p>
                    The <strong>Exception</strong> class is subclassed to created custom exception types to catch the
                    exceptional conditions encountered by the program.
                </p>
            </li>
            <li>
                <p>
                    The <strong>RunTimeException</strong> class is a subclass of <i>Exception</i>. The exceptions of
                    this type are automatically defined for the programs. Ex.: ArithmeticException,
                    IndexOutOfBoundsException, NullPointerException, etc.
                </p>
            </li>
            <li>
                <p>
                    Any exception that is not caught by your program will ultimately be processed by the default
                    handler. The default handler displays a string describing the exception, prints a stack trace from
                    the point at which exception has occured, and teminates the program.
                </p>
            </li>
            
            <br>
            <div class="syntax-container syntax-container-center syntax-std">

                <p style="font-weight: bold;">
                    Syntax:
                </p>
        
                <xmp>
                    try {
                    // block of code to monitor for errors
                    }
        
                    catch (ExceptionType1 exOb){
                    // exception handler for Exception Type 1
                    }
        
                    catch (ExceptionType2 exOb){
                    // exception handler for Exception Type 2
                    }
                    // ...
        
                    finally {
                    // block of code to be executed after try block ends
                    }
                </xmp>
            </div>

            <li>
                <p>
                    As soon as an exception is thrown the program control transfers out of the <strong>try</strong> block into the <strong>catch</strong> block. After the statements inside the <i>catch</i> block has executed, program control continues with the next set of statements following the entire <i>try-catch</i> module.
                </p>
            </li>
        </ul>
    </div>

    <br><br><br>

    <footer class="navigation-std">

        <ul class="ul-remove-bullet nav-pills">

            <li class="ul-inline-item nav-pills-decor">
                <a class="link" href="/">Previous</a>
            </li>

            <li class="ul-inline-item nav-pills-decor">
                <a class="link" href="/">Home</a>
            </li>

            <li class="ul-inline-item nav-pills-decor">
                <a class="link" href="/">Next</a>
            </li>

        </ul>

    </footer>

</body>

</html>